import { Restaurant, Listing, Order, User } from '../types';
import { addHours, addMinutes, subDays } from 'date-fns';

export const MOCK_USER: User = {
  id: 'user_1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'customer',
  address: '123 Emerald St, Pasig, Metro Manila',
  preferences: {
    dietary: ['Vegetarian']
  },
  impactStats: {
    mealsRescued: 12,
    co2Saved: 4.5,
    moneySaved: 2450
  },
  photoUrl: 'https://i.pravatar.cc/150?u=user_1'
};

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest_1',
    name: 'Jollibee',
    logo: 'https://yt3.googleusercontent.com/ytc/AIdro_moJ70yvGTY1KX6uNy70QA6ClIQmPcfs7862-aIEETYEfQ=s900-c-k-c0x00ffffff-no-rj',
    cover: 'https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_300,dpr_3/https://assets.app.engoo.com/images/1gU6gLS4GeHi1KMJ4IdZ48.jpeg',
    address: 'Victoria Plaza, J.P. Laurel Ave, Davao City',
    lat: 7.0862,
    lng: 125.6146,
    rating: 4.8,
    reviewsCount: 1250,
    pickupWindow: { start: '19:00', end: '21:00' },
    categories: ['Fast Food', 'Filipino'],
    distance: 0.5
  },
  {
    id: 'rest_2',
    name: "McDonald's Philippines",
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/McDonald%27s_square_2020.svg',
    cover: 'https://www.investopedia.com/thmb/a_tD7rBwlEFRJGL-yuZnbE7lnZY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/shutterstock_523483492-mcdonalds-5988b1ffc412440010f2d0b9.jpg',
    address: 'Bajada, Davao City',
    lat: 7.0877,
    lng: 125.6178,
    rating: 4.7,
    reviewsCount: 980,
    pickupWindow: { start: '20:00', end: '22:00' },
    categories: ['Fast Food', 'Burgers'],
    distance: 0.8
  },
  {
    id: 'rest_3',
    name: "Shakey's",
    logo: 'https://static.wixstatic.com/media/382e5f_0da015e4d1364af3b62ae16ab30dbcd7~mv2.jpg/v1/fill/w_480,h_480,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/382e5f_0da015e4d1364af3b62ae16ab30dbcd7~mv2.jpg',
    cover: 'https://insideretail.asia/wp-content/uploads/2020/09/Shakeys-Pizza.jpg',
    address: 'SM Lanang Premier, Davao City',
    lat: 7.0988,
    lng: 125.6312,
    rating: 4.6,
    reviewsCount: 560,
    pickupWindow: { start: '19:30', end: '21:00' },
    categories: ['Pizza', 'Italian'],
    distance: 1.5
  },
  {
    id: 'rest_4',
    name: 'Marina Tuna',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkxUUBH4kUwvCM5LMO5m7jslyM5_VFjZzPCA&s',
    cover: 'https://d3up48wss6lvj.cloudfront.net/data/uploads/2020/07/MARINA_TUNA.jpg',
    address: 'Sasa, Davao City',
    lat: 7.1147,
    lng: 125.6512,
    rating: 4.9,
    reviewsCount: 2100,
    pickupWindow: { start: '18:00', end: '20:00' },
    categories: ['Seafood', 'Filipino'],
    distance: 2.5
  },
  {
    id: 'rest_5',
    name: "Penong's",
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCyStCokzJfxq-GN5XhBX_nVWic4fPflSvXw&s',
    cover: 'https://ansi.ph/wp-content/uploads/2020/11/Penongs-Branch.jpg',
    address: 'Quirino Ave, Davao City',
    lat: 7.0712,
    lng: 125.6089,
    rating: 4.7,
    reviewsCount: 1540,
    pickupWindow: { start: '19:00', end: '21:00' },
    categories: ['BBQ', 'Filipino'],
    distance: 1.2
  },
  {
    id: 'rest_6',
    name: "Lachi's",
    logo: 'https://d3up48wss6lvj.cloudfront.net/data/uploads/2021/09/LACHI.png',
    cover: 'https://tourism.davaocity.gov.ph/wp-content/uploads/2019/08/lachi.jpeg',
    address: 'Marfori Heights, Davao City',
    lat: 7.0789,
    lng: 125.6123,
    rating: 4.9,
    reviewsCount: 890,
    pickupWindow: { start: '17:00', end: '19:00' },
    categories: ['Desserts', 'Filipino'],
    distance: 2.1
  },
  {
    id: 'rest_7',
    name: "Roxas Night Market",
    logo: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=200&h=200',
    cover: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800&h=400',
    address: 'Roxas Ave, Davao City',
    lat: 7.0701,
    lng: 125.6112,
    rating: 4.8,
    reviewsCount: 5000,
    pickupWindow: { start: '21:00', end: '23:59' },
    categories: ['Street Food', 'Filipino'],
    distance: 0.9
  },
  {
    id: 'rest_8',
    name: "Dunkin' Donuts",
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlaNBGXuGhBPTt27jnYcxlNThvVcWwGCmLZw&s',
    cover: 'https://media.newyorker.com/photos/5babed9459f95b2ce7bece4f/16:9/w_2560,h_1440,c_limit/Crouch-Dunkin-Donuts.jpg',
    address: 'Gaisano Mall of Davao, J.P. Laurel Ave, Davao City',
    lat: 7.0812,
    lng: 125.6123,
    rating: 4.6,
    reviewsCount: 3200,
    pickupWindow: { start: '18:00', end: '20:00' },
    categories: ['Bakery', 'Desserts', 'Drinks'],
    distance: 1.1
  },
  {
    id: 'rest_9',
    name: "Rose Bakeshop",
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdphYUpSw5Ay5Egq1WH9C3SbttAstYertq7g&s',
    cover: 'https://images.deliveryhero.io/image/fd-ph/LH/puya-listing.jpg',
    address: 'Bolton St, Davao City',
    lat: 7.0678,
    lng: 125.6089,
    rating: 4.5,
    reviewsCount: 1800,
    pickupWindow: { start: '17:30', end: '19:30' },
    categories: ['Bakery', 'Filipino'],
    distance: 0.7
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'list_1',
    restaurantId: 'rest_1',
    restaurantName: 'Jollibee',
    name: '2 - pc. Chickenjoy Solo',
    photo: 'https://images.yummy.ph/yummy/uploads/2023/05/jollibee-chickenjoymeal.jpg',
    description: 'The Best Fried Chicken! Crispylicious, Juicylicious! Jollibee\'s perfectly seasoned fried chicken that\'s crispy on the outside; tender and juicy on the inside.',
    originalPrice: 201,
    rescuePrice: 124,
    quantity: 3,
    expiryTime: addHours(new Date(), 2).toISOString(),
    category: 'Filipino',
    allergens: ['Gluten'],
    status: 'available'
  },
  {
    id: 'list_jollibee_2',
    restaurantId: 'rest_1',
    restaurantName: 'Jollibee',
    name: 'Burger Steak (Surplus)',
    photo: 'https://ilovetoeatph.files.wordpress.com/2019/06/2-1.jpg?w=1080&h=1080&crop=1',
    description: '100% beef patty with flavorful mushroom gravy. Still hot and delicious.',
    originalPrice: 150,
    rescuePrice: 85,
    quantity: 5,
    expiryTime: addHours(new Date(), 1).toISOString(),
    category: 'Fast Food',
    allergens: ['Gluten', 'Dairy'],
    status: 'available'
  },
  {
    id: 'list_2',
    restaurantId: 'rest_2',
    restaurantName: "McDonald's Philippines",
    name: 'Big Mac (Surplus)',
    photo: 'https://d3bjzufjcawald.cloudfront.net/public/web/2024-03-06/65e82c80d0140/Menu_Burgers_500x500_BigMac-500.jpg',
    description: 'The iconic Big Mac with two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.',
    originalPrice: 215,
    rescuePrice: 110,
    quantity: 4,
    expiryTime: addMinutes(new Date(), 45).toISOString(),
    category: 'Burgers',
    allergens: ['Gluten', 'Dairy'],
    status: 'available'
  },
  {
    id: 'list_mcdo_2',
    restaurantId: 'rest_2',
    restaurantName: "McDonald's Philippines",
    name: 'McDo Fries Large (Bundle of 3)',
    photo: 'https://d3bjzufjcawald.cloudfront.net/public/web/2024-03-07/65e934e80364e/Menu_Fries_500x500_FriesMedium-500.jpg',
    description: 'Our world-famous fries. Bundle of 3 large servings from the last hour.',
    originalPrice: 315,
    rescuePrice: 145,
    quantity: 2,
    expiryTime: addMinutes(new Date(), 30).toISOString(),
    category: 'Fast Food',
    allergens: [],
    status: 'available'
  },
  {
    id: 'list_3',
    restaurantId: 'rest_3',
    restaurantName: "Shakey's",
    name: 'Manager\'s Choice Party Pizza',
    photo: 'https://www.shakeys.com/img/party/partyimage2.jpg',
    description: 'Thin crust party size pizza. Last one from the display, still crispy.',
    originalPrice: 750,
    rescuePrice: 320,
    quantity: 1,
    expiryTime: addHours(new Date(), 1).toISOString(),
    category: 'Pizza',
    allergens: ['Gluten', 'Dairy'],
    status: 'available'
  },
  {
    id: 'list_shakeys_2',
    restaurantId: 'rest_3',
    restaurantName: "Shakey's",
    name: 'Chicken n\' Mojos (Surplus)',
    photo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg9Y2ww-Djgl175FencUH6TvWRZczDb6KPCi4jV0NHQHodm5fzw0yeXBEFT2C-TCf88Sb6cbg3JSLXfYc0s1vVnhwFclafODPkBoNNUSHjrOourJTlr2-pnPbGpeRnIcqbScSB3v7-q-mc/s1600/Chicken+%2527n+Mojos.png',
    description: 'A combination of fried chicken and our signature mojos. Bundle from lunch service.',
    originalPrice: 650,
    rescuePrice: 280,
    quantity: 2,
    expiryTime: addHours(new Date(), 2).toISOString(),
    category: 'Fast Food',
    allergens: ['Gluten'],
    status: 'available'
  },
  {
    id: 'list_4',
    restaurantId: 'rest_4',
    restaurantName: 'Marina Tuna',
    name: 'Grilled Tuna Belly Set',
    photo: 'https://media.pickaroo.com/media/thumb/product_photo/2022/1/6/EM93eafePAUdwWCyRwN93L_watermark_400.jpg',
    description: 'Davao\'s pride! Succulent grilled tuna belly served with rice.',
    originalPrice: 350,
    rescuePrice: 150,
    quantity: 5,
    expiryTime: addHours(new Date(), 3).toISOString(),
    category: 'Seafood',
    allergens: ['Fish'],
    status: 'available'
  },
  {
    id: 'list_marina_2',
    restaurantId: 'rest_4',
    restaurantName: 'Marina Tuna',
    name: 'Tuna Kinilaw (Fresh Surplus)',
    photo: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400&h=300',
    description: 'Raw tuna cubes marinated in vinegar and spices. Prepared fresh today.',
    originalPrice: 280,
    rescuePrice: 120,
    quantity: 3,
    expiryTime: addHours(new Date(), 1).toISOString(),
    category: 'Seafood',
    allergens: ['Fish'],
    status: 'available'
  },
  {
    id: 'list_penongs_1',
    restaurantId: 'rest_5',
    restaurantName: "Penong's",
    name: 'Chicken Inasal with Unli Rice',
    photo: 'https://www.manginasal.ph/wp-content/uploads/2023/09/chicken-insal-regular-3.png?q=80&w=1200&h=630',
    description: 'Grilled chicken marinated in special spices. Served with rice.',
    originalPrice: 185,
    rescuePrice: 95,
    quantity: 8,
    expiryTime: addHours(new Date(), 2).toISOString(),
    category: 'BBQ',
    allergens: [],
    status: 'available'
  },
  {
    id: 'list_5',
    restaurantId: 'rest_6',
    restaurantName: "Lachi's",
    name: 'Sans Rival Slice Bundle',
    photo: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400&h=300',
    description: 'Davao\'s best Sans Rival! A bundle of 3 slices from today\'s batch.',
    originalPrice: 420,
    rescuePrice: 180,
    quantity: 4,
    expiryTime: addHours(new Date(), 2).toISOString(),
    category: 'Desserts',
    allergens: ['Nuts', 'Dairy', 'Eggs'],
    status: 'available'
  },
  {
    id: 'list_lachis_2',
    restaurantId: 'rest_6',
    restaurantName: "Lachi's",
    name: 'Blueberry Cheesecake Slice',
    photo: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=400&h=300',
    description: 'Creamy cheesecake topped with sweet blueberries. Last few slices of the day.',
    originalPrice: 165,
    rescuePrice: 75,
    quantity: 6,
    expiryTime: addHours(new Date(), 3).toISOString(),
    category: 'Desserts',
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    status: 'available'
  },
  {
    id: 'list_6',
    restaurantId: 'rest_7',
    restaurantName: "Roxas Night Market",
    name: 'Street Food Feast (Large)',
    photo: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=400&h=300',
    description: 'A giant platter of charcoal grilled meats, kwek-kwek, and more!',
    originalPrice: 500,
    rescuePrice: 200,
    quantity: 10,
    expiryTime: addHours(new Date(), 4).toISOString(),
    category: 'Street Food',
    allergens: [],
    status: 'available'
  },
  {
    id: 'list_dunkin_1',
    restaurantId: 'rest_8',
    restaurantName: "Dunkin' Donuts",
    name: 'Assorted Donuts Dozen (Surplus)',
    photo: 'https://regalomanila.com/wp-content/uploads/2024/12/22795861.jpg',
    description: 'A dozen of our fresh, daily-made assorted donuts. Perfectly fine but needs to go before closing!',
    originalPrice: 450,
    rescuePrice: 220,
    quantity: 5,
    expiryTime: addHours(new Date(), 2).toISOString(),
    category: 'Bakery',
    allergens: ['Gluten', 'Eggs', 'Dairy'],
    status: 'available'
  },
  {
    id: 'list_dunkin_2',
    restaurantId: 'rest_8',
    restaurantName: "Dunkin' Donuts",
    name: 'Iced Coffee Bundle (Large x 2)',
    photo: 'https://images.summitmedia-digital.com/spotph/images/2024/04/05/dunkin-coffee-time-combo-promo-enhypen-1712311145.jpg',
    description: 'Two large iced coffees prepared in the last hour. Still cold and refreshing.',
    originalPrice: 280,
    rescuePrice: 135,
    quantity: 3,
    expiryTime: addMinutes(new Date(), 45).toISOString(),
    category: 'Drinks',
    allergens: ['Dairy'],
    status: 'available'
  },
  {
    id: 'list_rose_1',
    restaurantId: 'rest_9',
    restaurantName: "Rose Bakeshop",
    name: 'Fresh Pandesal Bundle (24 pcs)',
    photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSKoz_eYNRCD1WoIZzhfjHrpePpY7OPpT1-Q&s',
    description: 'Soft and warm pandesal. A large batch from this morning\'s bake.',
    originalPrice: 120,
    rescuePrice: 60,
    quantity: 10,
    expiryTime: addHours(new Date(), 4).toISOString(),
    category: 'Bakery',
    allergens: ['Gluten'],
    status: 'available'
  },
  {
    id: 'list_rose_2',
    restaurantId: 'rest_9',
    restaurantName: "Rose Bakeshop",
    name: 'Ensaymada Surprise Box',
    photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQftqL2g41M-OpmrojRao32XXs3rKTl4WBQxQ&s',
    description: 'A box of 6 assorted ensaymadas (cheese, ube, etc.). Still fluffy and delicious.',
    originalPrice: 300,
    rescuePrice: 145,
    quantity: 4,
    expiryTime: addHours(new Date(), 3).toISOString(),
    category: 'Bakery',
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    status: 'available'
  }
];


export const MOCK_ORDERS: Order[] = [
  {
    id: 'order_1',
    userId: 'user_1',
    restaurantId: 'rest_1',
    restaurantName: 'Bake My Day',
    items: [{ listingId: 'list_1', name: 'Pastry Surplus Box', price: 199, quantity: 1 }],
    total: 199,
    status: 'delivered',
    deliveryType: 'pickup',
    createdAt: subDays(new Date(), 1).toISOString()
  }
];
